plugins {
  id "application"
  id "java"
  id 'org.jsonschema2pojo' version '1.2.2'
  id "org.springframework.boot" version "3.4.5"
  id "io.spring.dependency-management" version "1.1.7"
}

group = "uk.gov.moj.cp"
version = "0.1.0"

java {
  sourceCompatibility = JavaVersion.VERSION_25
  targetCompatibility = JavaVersion.VERSION_25

  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

repositories {
  mavenCentral()
}

ext {
  lombokVersion = "1.18.42"
}

dependencies {
  implementation "org.springframework.boot:spring-boot-starter-web"
  implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"

  testImplementation(platform("org.junit:junit-bom:5.12.2"))
  testImplementation "org.springframework.boot:spring-boot-starter-test"
  testImplementation("org.junit.jupiter:junit-jupiter-api")
  testImplementation("org.junit.jupiter:junit-jupiter-params")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")

  compileOnly group: 'org.projectlombok', name: 'lombok', version: lombokVersion
  annotationProcessor group: 'org.projectlombok', name: 'lombok', version: lombokVersion

}

jsonSchema2Pojo {
  source = files("src/main/resources/schema") // <-- path to your JSON Schema files
  targetPackage = 'com.moj.generated'     // <-- your desired package name
  targetDirectory = file("$buildDir/generated-sources/js2p")
  includeGeneratedAnnotation = true
  usePrimitives = true
  includeConstructors = true
  annotationStyle = "jackson2"
  useJodaDates = false
  dateType = "java.time.LocalDate"
  dateTimeType = "java.time.ZonedDateTime"
}

sourceSets {
  main {
    java {
      srcDir "$buildDir/generated-sources/js2p"
    }
  }
}

application {
  mainClass = "uk.gov.moj.cp.Application"
  applicationName = "stg-track-my-case-service-mock"
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
}
