services:
  wiremock-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WIREMOCK_PORT: ${WIREMOCK_PORT:-8089}
    ports:
      - "${WIREMOCK_PORT:-8089}:${WIREMOCK_PORT:-8089}"
    networks:
      - tmc-mock

networks:
  tmc-mock:
    name: stg-track-my-case-mock
