server:
  port: ${SERVER_PORT:8089}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

services:
  # Mock response delay per controller (milliseconds)
  pcd_latency_millisecond: ${TMC_PCD_CONTROLLER_DELAY:10000}
  slc_latency_millisecond: ${TMC_COURT_HOUSE_CONTROLLER_DELAY:10000}
  rcc_latency_millisecond: ${TMC_COURT_SCHEDULE_CONTROLLER_DELAY:10000}
